version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-xampp-like
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: antam_db
    ports:
      - "8111:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
