version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: antam-mysql
    restart: unless-stopped
    ports:
      - "8111:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: antam_bot
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
